from __future__ import annotations

TACTIC_SEEDS = [
    {
        "id": "T001",
        "name": "Counter Block",
        "content": "When the opponent hits a heavy smash deep into your court, use a soft backhand block to the net and force them forward.",
        "tag": "defense",
        "style_family": "absorb-and-redirect",
        "tempo_band": "fast",
        "phase_preference": "under_pressure",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["Power Smash", "Steep Smash", "Smash", "Pressure Rally"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 90,
        "speed_max": 260,
        "court_contexts": ["rear_channel", "rear_wide", "mid_channel"],
        "risk_level": "medium",
        "recovery_cost": 0.46,
        "pressure_gain": 0.84,
    },
    {
        "id": "T002",
        "name": "Deep Lift Reset",
        "content": "On a high serve return, if the opponent stands too far forward, lift quickly to the rear corners and reset the rally.",
        "tag": "attack",
        "style_family": "reset-and-rebuild",
        "tempo_band": "medium",
        "phase_preference": "neutral",
        "preferred_last_hitter": "USER",
        "applicable_events": ["Pressure Rally", "Drive Exchange", "Control Rally"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 40,
        "speed_max": 180,
        "court_contexts": ["front_central", "mid_central", "front_channel"],
        "risk_level": "low",
        "recovery_cost": 0.34,
        "pressure_gain": 0.58,
    },
    {
        "id": "T003",
        "name": "Cross Drop Finish",
        "content": "When your net spin quality is high, stay forward and be ready to punish the loose cross-court reply.",
        "tag": "net",
        "style_family": "front-court-trap",
        "tempo_band": "controlled",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["Control Rally", "Pressure Rally", "Net Control"],
        "preferred_match_types": ["singles"],
        "speed_min": 25,
        "speed_max": 120,
        "court_contexts": ["front_central", "front_channel"],
        "risk_level": "medium",
        "recovery_cost": 0.42,
        "pressure_gain": 0.79,
    },
    {
        "id": "T004",
        "name": "Straight Relief Clear",
        "content": "During a pressured backhand transition, play a straight high clear to reduce interception risk.",
        "tag": "defense",
        "style_family": "reset-and-rebuild",
        "tempo_band": "medium",
        "phase_preference": "under_pressure",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["Pressure Rally", "Drive Exchange", "Smash"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 55,
        "speed_max": 170,
        "court_contexts": ["mid_wide", "rear_wide", "mid_channel"],
        "risk_level": "low",
        "recovery_cost": 0.28,
        "pressure_gain": 0.49,
    },
    {
        "id": "T005",
        "name": "Four Corners Grind",
        "content": "When the opponent starts to slow down physically, stretch them across all four corners to drain the remaining legs.",
        "tag": "tactic",
        "style_family": "attritional-pressure",
        "tempo_band": "controlled",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["Control Rally", "Pressure Rally"],
        "preferred_match_types": ["singles"],
        "speed_min": 20,
        "speed_max": 130,
        "court_contexts": ["mid_central", "rear_central", "mid_channel"],
        "risk_level": "medium",
        "recovery_cost": 0.52,
        "pressure_gain": 0.82,
    },
    {
        "id": "T006",
        "name": "Body Drive Jam",
        "content": "In a flat exchange, drive hard through the opponent's right shoulder to crowd their contact zone and force a weak reply.",
        "tag": "attack",
        "style_family": "compression-attack",
        "tempo_band": "fast",
        "phase_preference": "neutral",
        "preferred_last_hitter": "USER",
        "applicable_events": ["Drive Exchange", "Pressure Rally"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 85,
        "speed_max": 210,
        "court_contexts": ["mid_central", "mid_channel", "front_central"],
        "risk_level": "medium",
        "recovery_cost": 0.55,
        "pressure_gain": 0.88,
    },
    {
        "id": "T007",
        "name": "Rear Court Hold Flick",
        "content": "Show the straight drop shape from the rear court, then flick sharply over the opponent to break their base timing.",
        "tag": "attack",
        "style_family": "deception",
        "tempo_band": "medium",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["Control Rally", "Pressure Rally", "Steep Smash"],
        "preferred_match_types": ["singles"],
        "speed_min": 60,
        "speed_max": 170,
        "court_contexts": ["rear_central", "rear_channel"],
        "risk_level": "high",
        "recovery_cost": 0.61,
        "pressure_gain": 0.9,
    },
    {
        "id": "T008",
        "name": "Serve Return Net Clamp",
        "content": "After a short serve or soft opening, hold the net with tight tape pressure and deny the opponent a comfortable lift.",
        "tag": "net",
        "style_family": "front-court-trap",
        "tempo_band": "controlled",
        "phase_preference": "advantage",
        "preferred_last_hitter": "USER",
        "applicable_events": ["Net Control", "Control Rally"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 10,
        "speed_max": 90,
        "court_contexts": ["front_central", "front_wide", "front_channel"],
        "risk_level": "low",
        "recovery_cost": 0.25,
        "pressure_gain": 0.76,
    },
    {
        "id": "T009",
        "name": "Midcourt Intercept Swipe",
        "content": "Step in on the next flat ball and take it early in front of the body to cut off the rally before it resets.",
        "tag": "attack",
        "style_family": "interception",
        "tempo_band": "fast",
        "phase_preference": "transition",
        "preferred_last_hitter": "OPPONENT",
        "applicable_events": ["Drive Exchange", "Pressure Rally", "Fast Flat Exchange"],
        "preferred_match_types": ["doubles", "singles"],
        "speed_min": 95,
        "speed_max": 230,
        "court_contexts": ["mid_central", "mid_channel", "front_channel"],
        "risk_level": "high",
        "recovery_cost": 0.66,
        "pressure_gain": 0.93,
    },
    {
        "id": "T010",
        "name": "Emergency Half Smash",
        "content": "When full elevation is gone, use a steep half smash into the body to keep attack without overcommitting your base.",
        "tag": "tactic",
        "style_family": "managed-pressure",
        "tempo_band": "medium-fast",
        "phase_preference": "transition",
        "preferred_last_hitter": "USER",
        "applicable_events": ["Pressure Rally", "Control Rally", "Steep Smash"],
        "preferred_match_types": ["singles", "doubles"],
        "speed_min": 70,
        "speed_max": 185,
        "court_contexts": ["rear_central", "rear_channel", "mid_central"],
        "risk_level": "medium",
        "recovery_cost": 0.44,
        "pressure_gain": 0.74,
    },
]

TACTIC_NAME_BY_ID = {seed["id"]: seed["name"] for seed in TACTIC_SEEDS}
